apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debian-app
  template:
    metadata:
      labels:
        app: debian-app
    spec:
      containers:
        - name: debian-container
          image: debian:bullseye
          ports:
            - containerPort: 80
