apiVersion: v1
kind: ConfigMap
metadata:
  name: root-cert-config
data:
  cert1: |
    -----BEGIN CERTIFICATE-----
    MIIDdzCCAl+gAwIBAgIJAIBsI7JEX/b6MA0GCSqGSIb3DQEBCwUAMF0xCzAJBgNV
    BAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRIwEAYDVQQHDAlTYW4gRGllZ28x
    GTAXBgNVBAoMEENlcnRpZmljYXRlIFNlcnZpY2VzMB4XDTIxMDQxNTA2NTIzOVoX
    DTIyMDQxNTA2NTIzOVowXTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3Ju
    aWExEjAQBgNVBAcMCVNhbiBEaWVnbzEZMBcGA1UECgwQQ2VydGlmaWNhdGUgU2Vy
    dmljZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAq45by6C1t1Qt
    5cG68ZX0doH+ftgB/IDZ1VKnR6z6B34iWa5sHsl2kQvKvzP/svEbkd7d0zC5EmTk
    3FohkHb2KjvftlFmiO0mXw2Pafyb4O39C2vmMn5bG5pWtXbq7+tJk2pbgRPExyG0
    tLP1JcBvl6DVC6EFONK/EURs0Ml9AFxbZwoZNYPRDAS5M4TO+Jhzxnxd1UAYTY5J
    n31JswVhuPm0zmp1WxagvFjLrwAl9S4MGAg+5uQS4mKEbuzljGzk64mYVztVWtnM
    h9ax3a5O8I4nTZr5jl8XjMgCgYEA2A79tv5P3Pbdod5bU45rY+lxJsChmCZ8V+iG
    gsCJkM21Cf4AfF6O8Jxt0MRDKMYB9J4DBX0po02NmyM3smkCAwEAAaNTMFEwHQYD
    VR0OBBYEFMpphTT1zP+2zC6fE8QuH7H8QNLJMB8GA1UdIwQYMBaAFMpphTT1zP+2
    zC6fE8QuH7H8QNLJMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
    ADLTOKLff8Ro7mGqiJ12bd1uNphOxl1uKsQqCy1hO/j5CgVtR+5rL1DoV5RLGdj+
    iIYMc7sYy3mdBWVSsnyAzY5CqqZ5AWK1rleEGH5KkmFOpT+NT5Cw3WWcl9o7MgyY
    E6Z+qiKR6tbm5A/QGdtm+k2vyrTk5/8NVRYHhxpjHkq9Onr6KmUO6BLrRrYWJ1F3
    QGC5T0r3Y0Hp9zB0E9Ghb5sF/gApVQkwpUlXgHT+jZ+mThIlG7Vc/jZgGz/B4WFx
    xVtqT6yCoZw4k0aWyN4VQKVP+6GFDyDNNQJ7Vbm/X2tlQLIM1jLDvclSohcAeFZ/
    RixL9B7jFS/Nmkt4+X6PnD8=
    -----END CERTIFICATE-----
  cert2: |
    -----BEGIN CERTIFICATE-----
    MIIFITCCBAmgAwIBAgIQE+hSLXQTlIkJIopC6ndWjDANBgkqhkiG9w0BAQsFADA7
    MQswCQYDVQQGEwJVUzEeMBwGA1UEChMVR29vZ2xlIFRydXN0IFNlcnZpY2VzMQww
    CgYDVQQDEwNXUjMwHhcNMjQxMDAxMTUwMTUzWhcNMjQxMjMwMTU1MjQ1WjAWMRQw
    EgYDVQQDEwtkZW5jb2RlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBAK6QTFJ6XYq4C7qiOlI2RIsUxOhO5h4LLHsgdzB3ywizSoJQxO0msOGKg1QR
    coWPnrv+Zzh/qofFxp6Ep4HtRqmbA95SL64QMEL/PdbkZXWvSlqh/PO/SdqLEMCg
    m79lxglxJB1mCEj2kUOE9ph0l8mT6V8VZNW08QA28NATrMranxBF4FKu79eR4wbV
    0Su+wN7SZespHmMeqpAXfbRBHt7R5Q1yOPxUV3XSzHbJdOu9RiqvlMt3d25HMGB+
    lEPA/YETfDZ5XFRNQf/+3BexnmFsioCQJ1165L937Z4RRALr+7g+VWdZ7DPVXvvU
    w/Um/ZWr6BjrRWJT8uf10m08wZkCAwEAAaOCAkQwggJAMA4GA1UdDwEB/wQEAwIF
    oDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBS6
    A1Qp45XTpVGjn1yGdq6Lsom7QTAfBgNVHSMEGDAWgBTHgfX9jojZADxNY6JQMSSg
    ziP+IzBeBggrBgEFBQcBAQRSMFAwJwYIKwYBBQUHMAGGG2h0dHA6Ly9vLnBraS5n
    b29nL3Mvd3IzL0UtZzAlBggrBgEFBQcwAoYZaHR0cDovL2kucGtpLmdvb2cvd3Iz
    LmNydDAWBgNVHREEDzANggtkZW5jb2RlLmNvbTATBgNVHSAEDDAKMAgGBmeBDAEC
    ATA2BgNVHR8ELzAtMCugKaAnhiVodHRwOi8vYy5wa2kuZ29vZy93cjMvN2hpUUVN
    NHBPSVkuY3JsMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYAdv+IPwq2+5VRwmHM
    9Ye6NLSkzbsp3GhCCp/mZ0xaOnQAAAGSSNETMgAABAMARzBFAiBu90pPJ/VUmaOG
    ovJKoMFyvsNatD1QOM6tSRfAdddTfQIhANGJALWv84+fn0uV6ONzsRKm+J3S2AkG
    oh7VwiG4jv36AHYASLDja9qmRzQP5WoC+p0w6xxSActW3SyB2bu/qznYhHMAAAGS
    SNETJQAABAMARzBFAiAQPSMYznRWsl+GY2yopQMIGjNWjG8eTLSWi9J5+YIbDgIh
    AIQo80X7qSlJN+DhomZHbzSMbfY3RV4QwaUrGvVVSbeKMA0GCSqGSIb3DQEBCwUA
    A4IBAQA0OsB4MTwCupNsR0LG4q9SBUdTyoeTrwSmk5H55InvZVVSxDQY0hTJGaPE
    IHttH8tQgMpOtN6OzAiGi8wa1cp5JRDycRx+3dli8FtoywP0DsN5T5IoDN/FT5vY
    YGGGXPzv/k18OHEFsp2RYQB5q0oXWA2OZQ848cSJlpcLn+k2ISpI5umyoe9aDbQK
    BjRF5oDsjL1JyFj79dILi4O8kAJCudb90b97QFu5Gd5bEMGHdKwsZTN7/lvotjc5
    JaiVyfaYDx2nN40QKJmMS823/JIN+fYQOxAiTSkCsYpncuNpXL26Y7nXcKUeyb5x
    W4QulthZx87rC2vD1sK4GMc+xgE5
    -----END CERTIFICATE-----

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian-app
  template:
    metadata:
      labels:
        app: debian-app
    spec:
      initContainers:
      - name: init-cert-container
        image: debian:bullseye
        command: ["/bin/sh", "-c"]
        args: ["apt-get update && apt-get install -y ca-certificates && cp /etc/certs/cert1 /usr/local/share/ca-certificates/ && cp /etc/certs/cert2 /usr/local/share/ca-certificates/; update-ca-certificates"]
        volumeMounts:
        - name: cert1
          mountPath: /etc/certs/cert1
          subPath: cert1
        - name: cert2
          mountPath: /etc/certs/cert2
          subPath: cert2
      containers:
      - name: debian-container
        image: debian:bullseye
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cert1
          mountPath: /etc/certs/cert1
          subPath: cert1
        - name: cert2
          mountPath: /etc/certs/cert2
          subPath: cert2
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: cert1
        configMap:
          name: root-cert-config
          items:
            - key: cert1
              path: cert1
      - name: cert2
        configMap:
          name: root-cert-config
          items:
            - key: cert2
              path: cert2
