apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debian-app
  template:
    metadata:
      labels:
        app: debian-app
    spec:
      containers:
      - name: debian-container
        image: debian:bullseye
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
