apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-ngnix
  namespace: argocd  # Namespace where Argo CD itself is deployed

spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/values/nginx.yaml
  - repoURL: 'https://github.com/mike-munro/argo-apps-of-apps.git'
    targetRevision: main
    ref: values

  destination:
    namespace: default  # Target namespace where the application will be deployed
    server: https://kubernetes.default.svc  # Kubernetes API server URL
  project: default  # Argo CD project to which this application belongs
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  # Option to create the target namespace if it doesn't exist during synchronization
    automated:
      selfHeal: true  # Enable self-healing to reconcile the application state
      prune: true  # Enable pruning to delete resources that are no longer specified in Git

