apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prometheus
  namespace: argocd  # Namespace where Argo CD itself is deployed

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - chart: elasticsearch
      repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
    - repoURL: https://github.com/mike-munro/argo-apps-of-apps.git
      path: charts
      targetRevision: main