apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: synopsis-project
  namespace: srm
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: srm
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
